# theme="default"
# theme = "gruvbox_dark_hard"
# theme = "kaolin-valley-dark"
# theme = "github_dark_tritanopia"
# theme = "seoul256-dark-hard"
# theme = "fleet_dark"
# theme = "darcula-solid"
# theme = "amberwood"
# theme = "carbonfox"
theme = "kanagawaT"
# theme = "tokyonightT"

[editor]
line-number = "relative"
mouse = true
true-color = true
auto-completion = true
auto-format = true
auto-save = true
color-modes = true
bufferline = 'multiple'
cursorline = true
soft-wrap.wrap-at-text-width = true
lsp.display-inlay-hints = true
end-of-line-diagnostics = "hint"
rulers = [80, 120]

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.file-picker]
hidden = true

[editor.whitespace]
#render = "all"

[editor.indent-guides]
#render = true
#character = "╎"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
#left = ["mode", "spinner", "file-name", "version-control"]
left = ["mode", "spinner", "file-name", "file-type", "total-line-numbers", "file-encoding"]
center = []
right = ["selections", "primary-selection-length", "position", "position-percentage", "spacer", "diagnostics", "workspace-diagnostics", "version-control"]

[keys.normal]
0 = "goto_line_start"
"$" = "goto_line_end"
Y = ["select_mode","goto_line_end", "yank_main_selection_to_clipboard"]
D = ["select_mode","goto_line_end", "delete_selection"]
# j = "move_visual_line_up"
# k = "move_visual_line_down"
ret = "goto_word"
X = "select_line_above"
A-x = "extend_to_line_bounds"
C-v = [":new",":insert-output lf-pick",":theme default","select_all","split_selection_on_newline","goto_file","goto_last_modified_file",":buffer-close!",":theme kanagawaT"]
# "C" = ["select_mode","goto_line_end", "change_selection"]
# esc = ["collapse_selection","keep_primary_selection"]

[keys.select]
X = "select_line_above"
A-x = "extend_to_line_bounds"

[keys.normal."space"]
v = ":w"
m = ":run-shell-command cargo build"
q = ":buffer-close-others"
ret = ":open %sh{~/.config/helix/yazi-picker.sh '%{buffer_name}'}"
i = ":sh zellij run --floating --name lazygit --height 90%% --width 90%% --x 10 --y 5 --close-on-exit -- lazygit"
l = ":sh zellij run --floating --name blame --height 90%% --width 90%% --x 10 --y 5 --close-on-exit -- tig blame '%{buffer_name}' +'%{cursor_line}'"
C-d = ":sh zellij run --floating --name diff --height 90%% --width 90%% --x 10 --y 5 --close-on-exit -- git diff"
n = ":sh zellij run --floating --name navi --height 90%% --width 90%% --x 10 --y 5 --close-on-exit -- navi"
C-q = ":sh zellij run --floating --name lazysql --height 90%% --width 90%% --x 10 --y 5 --close-on-exit -- lazysql"
C-r = ":sh zellij run --floating --name run --height 90%% --width 90%% --x 10 --y 5 --close-on-exit -- cargo run"
C-k = ":sh zellij run --floating --name check --height 90%% --width 90%% --x 10 --y 5 -- cargo check"
C-y = ":sh zellij run --floating --name clippy --height 90%% --width 90%% --x 10 --y 5 -- cargo clippy"

# i = [":new", ":insert-output lazygit", ":buffer-close!",":redraw"]
#C-f = [":new", ":insert-output lf-pick", ":theme default", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!", ":theme kanagawaT"]
# l = ":sh helix-wezterm.sh blame %{buffer_name} %{cursor_line}"
# C-c = ":sh helix-wezterm.sh check"
# ret = ":sh helix-wezterm.sh explorer"
# i = ":sh helix-wezterm.sh lazygit"
# o = ":sh helix-wezterm.sh open %{buffer_name} %{cursor_line}"
# C-q = ":sh helix-wezterm.sh query"
# C-r = ":sh helix-wezterm.sh run %{buffer_name}"
# C-s = ":sh helix-wezterm.sh slumber"
# #m = ":sh helix-wezterm.sh mock"
# n = ":sh helix-wezterm.sh navi"
# C-p = ":sh helix-wezterm.sh present %{buffer_name}"
# t = ":sh helix-wezterm.sh test %{buffer_name}"
# e = [
#   ":sh rm -f /Users/amansingh/tmp/unique-file-h21a434",
#   ':insert-output yazi %{buffer_name} --chooser-file=/Users/amansingh/tmp/unique-file-h21a434',
#   ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
#   ":open %sh{cat /Users/amansingh/tmp/unique-file-h21a434}",
#   ":redraw",
# ]


[keys.insert]
C-l = "move_char_right"
# C-s = ["normal_mode",":w"]
# C-h = ["move_prev_word_start"]
# C-s = ["normal_mode",":w"]
# C-x = "normal_mode"

